chatnoir/chatnoir_frontend/urls.py
# Copyright 2021 Janek Bevendorff
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.urls import path

from . import views

app_name = 'chatnoir_frontend'

urlpatterns = [
    path(r'', views.index, name='index'),

    # API key requests forms
    path(r'apikey/', views.index, name='apikey_request_index'),
    path(r'apikey/request-academic', views.apikey_request_academic, name='apikey_request_academic'),
    path(r'apikey/request-passcode', views.apikey_request_passcode, name='apikey_request_passcode'),
    path(r'apikey/request-received', views.index, name='request_received'),
    path(r'apikey/verify/', views.apikey_request_verify, name='apikey_request_verify_index'),
    path(r'apikey/verify/<slug:activation_code>', views.apikey_request_verify, name='apikey_request_verify'),

    # API Docs
    path(r'docs/', views.docs, name='docs_index'),
    path(r'docs/api-general', views.docs, name='docs_api_general'),
    path(r'docs/api-advanced', views.docs, name='docs_api_advanced'),
    path(r'docs/api-advanced/management', views.docs, name='docs_api_advanced_management'),

    # Cache redirect
    path(r'cache', views.cache, name='cache'),
]

chatnoir/chatnoir_frontend/templates/docs/api_advanced.html
{% extends "../index.html" %}
{% load chatnoir_tags %}
{% block title %}{% app_name %} API Documentation: Advanced API{% endblock %}
{% block after_app %}
    <template id="doc">
        <nav aria-label="Breadcrumb" class="text-sm border-b-1 pb-1">
            <a href="{% url 'chatnoir_frontend:docs_index' %}">ChatNoir API Documentation</a> »
            Advanced API
        </nav>

        <h1 id="advanced-api"><a href="#advanced-api" class="anchor-link">Advanced API</a></h1>

        <p>In addition to ChatNoir's <a href="{% url "chatnoir_frontend:docs_api_general" %}">general read-only search API</a>, we provide an
            advanced management API. Most of these features can be used only by privileged users. Privileges are granted by assigning
            specific user roles. If you need access to these advanced features, please contact us and state your use case.</p>

        <p>While the general syntax and API features are the same as for the read-only search API, there is usually a functional
            difference between <code>GET</code> and <code>POST</code> requests when using these advanced API features.</p>

        <p>API key authentication is required for all API calls.</p>

        <h2 id="available-endpoints"><a href="#advanced-api" class="anchor-link">Available Endpoints</a></h2>
        <ul class="my-4">
            <li class="mt-3">
                <a href="{% url "chatnoir_frontend:docs_api_advanced_management" %}">API Key Management</a>
                <p class="mt-0 text-sm">Privileged API endpoints for managing and issuing new API keys.</p>
        </ul>
    </template>
{% endblock %}

chatnoir/chatnoir_frontend/templates/docs/index.html
{% extends "../index.html" %}
{% load chatnoir_tags %}
{% block title %}{% app_name %} API Documentation{% endblock %}
{% block after_app %}
    <template id="doc">
        <h1 class="h1">{% app_name %}  API Documentation</h1>

        <p>The following API documentation resources are available:</p>

        <ul class="my-4">
            <li class="mt-3">
                <a href="{% url "chatnoir_frontend:docs_api_general" %}">General Search API</a>
                <p class="mt-0 text-sm">The main ChatNoir search API for term search and phrase search.</p>
            </li>
            <li class="mt-3">
                <a href="{% url "chatnoir_frontend:docs_api_advanced" %}">Advanced API</a>
                <p class="mt-0 text-sm">Additional API features.</p>
                <ul class="ml-6">
                    <li class="mt-3">
                        <a href="{% url "chatnoir_frontend:docs_api_advanced_management" %}">API Key Management</a>
                        <p class="mt-0 text-sm">Privileged API endpoints for managing and issuing new API keys.</p>
                    </li>
                </ul>
            </li>
        </ul>
    </template>
{% endblock %}